In [1]:
import numpy as np

np.__version__

'1.26.0'

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

In [9]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

In [10]:
arr = np.random.random(10)
arr[::-1]

array([0.33709483, 0.18355804, 0.94978234, 0.74844414, 0.23923481,
       0.41066112, 0.66298945, 0.60087867, 0.04197241, 0.97243516])

In [12]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [20]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

In [37]:
np.zeros((5, 5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [38]:
matrix = np.random.random((10, 10))
matrix - matrix.mean(axis=1, keepdims=True)
matrix

array([[0.20076333, 0.54078335, 0.60810778, 0.85504743, 0.71766874,
        0.67115348, 0.62383172, 0.11368979, 0.43819896, 0.49417696],
       [0.00989127, 0.09516053, 0.53221964, 0.90406288, 0.62263741,
        0.67358975, 0.91159723, 0.47057773, 0.32179735, 0.27424289],
       [0.13807122, 0.43809636, 0.63192258, 0.10877093, 0.76924617,
        0.63221643, 0.07291979, 0.76215963, 0.70241166, 0.85746365],
       [0.62751111, 0.13840992, 0.48536992, 0.84885133, 0.65351486,
        0.64589744, 0.16383903, 0.39399169, 0.52765697, 0.84355119],
       [0.8697842 , 0.94621141, 0.57923916, 0.42471761, 0.94776422,
        0.01080672, 0.79607927, 0.62183083, 0.89005973, 0.3314787 ],
       [0.10643856, 0.9463068 , 0.3780384 , 0.39793634, 0.37894244,
        0.84956697, 0.15212089, 0.81993973, 0.12568288, 0.69206259],
       [0.43735773, 0.2008287 , 0.27042372, 0.9590061 , 0.33875609,
        0.2299896 , 0.28176991, 0.11144432, 0.06102149, 0.28475791],
       [0.01691453, 0.34979056, 0.3084158

In [40]:
matrix = np.random.random((10, 10))
matrix - np.median(matrix, axis=0, keepdims=True)
matrix

array([[0.98984649, 0.49051037, 0.29829717, 0.35716092, 0.3666411 ,
        0.70549203, 0.76525171, 0.12646182, 0.75733613, 0.89472513],
       [0.47502115, 0.75324768, 0.28736575, 0.96444495, 0.08475518,
        0.40029788, 0.52760542, 0.2973521 , 0.29352709, 0.90328935],
       [0.70500088, 0.32490116, 0.76073138, 0.93881013, 0.21050328,
        0.42437628, 0.30560279, 0.8409756 , 0.22960748, 0.57132771],
       [0.55095305, 0.61935713, 0.48127461, 0.18429386, 0.71287595,
        0.02401582, 0.09337999, 0.19013899, 0.18619791, 0.29072363],
       [0.87309876, 0.69224481, 0.02585762, 0.55746841, 0.45063132,
        0.80934197, 0.14641858, 0.32682294, 0.50465696, 0.21852247],
       [0.72985751, 0.18991428, 0.80768562, 0.37192953, 0.3662858 ,
        0.90737566, 0.56634686, 0.60565106, 0.77302795, 0.67176283],
       [0.84205334, 0.78844362, 0.20174676, 0.35681012, 0.34624906,
        0.70547365, 0.76646698, 0.64094988, 0.12976579, 0.56455678],
       [0.76023501, 0.25956195, 0.2554417

In [43]:
matrix = np.random.random((5, 5))
matrix = np.hstack(
    (matrix, matrix.max(axis=1, keepdims=True), matrix.min(axis=1, keepdims=True))
)

print(matrix)
print(matrix.shape)

[[0.01214889 0.52337612 0.53656063 0.85033281 0.82687396 0.85033281
  0.01214889]
 [0.54990187 0.56640807 0.82523078 0.09124619 0.26248989 0.82523078
  0.09124619]
 [0.89525411 0.14322292 0.46725402 0.80076658 0.4369967  0.89525411
  0.14322292]
 [0.31720917 0.54414509 0.77895874 0.8815335  0.13120388 0.8815335
  0.13120388]
 [0.60614139 0.91161271 0.26982348 0.98425927 0.27606304 0.98425927
  0.26982348]]
(5, 7)


In [53]:
matrix = np.arange(1, 51)
evenMatrix = matrix[matrix % 2 == 0].reshape(5, 5)
oddMatrix = matrix[matrix % 2 == 1].reshape(5, 5)

print(f'Четная матрица:\n{evenMatrix}')
print(f'Нечетная матрица:\n{oddMatrix}')

multipleMatrix = evenMatrix @ oddMatrix

print(f'Произведение матриц:\n{multipleMatrix}')
print(f'Обратная матрица:\n{np.linalg.inv(multipleMatrix)}')


Четная матрица:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
Нечетная матрица:
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
Произведение матриц:
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]
Обратная матрица:
[[ 1.97032484e+13 -1.01330992e+14  1.68884986e+14 -1.12589991e+14
   2.53327479e+13]
 [-4.01101842e+13  1.66070236e+14 -2.43944980e+14  1.50119988e+14
  -3.21350598e+13]
 [ 2.11106233e+13 -2.81474977e+13 -0.00000000e+00 -0.00000000e+00
   7.03687442e+12]
 [-7.03687442e+11 -3.65917470e+13  5.62949953e+13  0.00000000e+00
  -1.89995609e+13]
 [ 5.20833333e-04 -0.00000000e+00  1.87649984e+13 -3.75299969e+13
   1.87649984e+13]]


In [57]:
chessboard_tile = np.array([[0, 1], [1, 0]])
np.tile(chessboard_tile, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])